#!/bin/sh

# Remap key, run hotkey daemon
remaps &
sxhkd &

# Status bar
dwmblocks &

# Wallpaper
xwallpaper --zoom $HOME/.local/config/wallpaper.png &

# ibus
ibus-daemon -drx

# compositor
picom &

# unclutter
unclutter &

# Use xresources
xrdb $HOME/.local/config/x/Xresources &

# Activate dbus variables
dbus-update-activation-environment --all

# Run dwm
exec dbus-launch --exit-with-session dwm
