set encoding=utf-8

""" Vundle plugin manager
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
    Plugin 'VundleVim/Vundle.vim'
    Plugin 'preservim/nerdtree'
    Plugin 'Xuyuanp/nerdtree-git-plugin'
    Plugin 'preservim/nerdcommenter'
    Plugin 'easymotion/vim-easymotion'
    Plugin 'morhetz/gruvbox'
    Plugin 'neoclide/coc.nvim', {'branch': 'release'}
    Plugin 'dense-analysis/ale'
    Plugin 'jiangmiao/auto-pairs'
    Plugin 'tpope/vim-surround'
call vundle#end()            " required
filetype plugin indent on    " required

""" move .viminfo to .vim/viminfo
set viminfo+=n~/.vim/viminfo

""" theme
let g:gruvbox_contrast_dark='hard'
let g:gruvbox_number_column='bg0'
colorscheme gruvbox
set bg=dark

""" set relative line number
set number relativenumber

""" space key as leader
let mapleader = " "

""" Set cursor shape
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

"reset cursor shape on start:
autocmd VimEnter * silent !echo -ne "\e[2 q"

""" Key, keycode delay
set timeoutlen=1000 ttimeoutlen=0

""" map Enter to new line
nmap <cr> o<esc>

" Disable auto comment
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

""" split navigations
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

""" disable Ex mode
map Q <Nop>

""" Indentation 
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab autoindent

""" enable syntax highlighting
syntax enable

""" enable all Python syntax highlighting features
let python_highlight_all = 1

""" nerdtree
" toggle
map <C-n> :NERDTreeToggle<CR>

" close vim if the only window left open is a NERDTree
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

""" easymotion 
map <Leader> <Plug>(easymotion-prefix)

""" vim tabs, used in status line
function MyTabLine()
    let s = ''
    let t = tabpagenr()
    let i = 1
    while i <= tabpagenr('$')
        let buflist = tabpagebuflist(i)
        let winnr = tabpagewinnr(i)
        let s .= (i == t ? ' | [[ ' : ' | ')
        let s .= i . ':'
        let bufnr = buflist[winnr - 1]
        let file = bufname(bufnr)
        let buftype = getbufvar(bufnr, 'buftype')
        if buftype == 'nofile'
            if file =~ '\/.'
            let file = substitute(file, '.*\/\ze.', '', '')
            endif
        else
            let file = fnamemodify(file, ':p:t')
        endif
        if file == ''
            let file = 'No Name'
        endif
        let s .= file
        let s .= (i == t ? '* ]]' : '')
        let i = i + 1
    endwhile
    let s.= ' |'
    return s
endfunction

""" CoC
" TextEdit might fail if hidden is not set.
set hidden

" use <tab> for trigger completion and navigate to the next complete item
function! s:check_back_space() abort
   let col = col('.') - 1
   return !col || getline('.')[col - 1]  =~ '\s'
endfunction
inoremap <silent><expr> <Tab>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<Tab>" :
        \ coc#refresh()

" goto code navigations
nmap <leader>gd <Plug>(coc-definition)
nmap <leader>gr <Plug>(coc-references)

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Some servers have issues with backup files, see #649.
set nobackup
set nowritebackup

" Having longer updatetime (default is 4000 ms = 4 s) leads to noticeable delays and poor user experience.
set updatetime=300

" Don't pass messages to |ins-completion-menu|.
set shortmess+=c

" Always show the signcolumn as number column
set signcolumn=number

" Use K to show documentation in preview window.
nnoremap <leader>k :call <SID>show_documentation()<CR>

function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
    else
        call CocActionAsync('doHover')
    endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

""" ALE
" set python linters
let g:ale_linters = {'python': ['flake8', 'pylint']}

" set python fixers
let g:ale_fixers = {'python': ['yapf']}

" map F7 to alefix
nmap <F7> :ALEFix<CR>

" function that show number of errors and warnings on statusline
function! LinterStatus() abort
    let l:counts = ale#statusline#Count(bufnr(''))
    let l:all_errors = l:counts.error + l:counts.style_error
    let l:all_non_errors = l:counts.total - l:all_errors
    return l:counts.total == 0 ? '' : printf(' %d  %d', all_non_errors, all_errors)
endfunction

""" status line
" hide actual tabline
set showtabline=0

" always show status
set laststatus=2

" tab color
highlight PmenuSel ctermfg=15 ctermbg=23

" set statusline
set statusline=
set statusline+=%#PmenuSel#
set statusline+=%{MyTabLine()}
set statusline+=%#LineNr#\   
set statusline+=%=
set statusline+=%#CursorColumn#
set statusline+=\ %{coc#status()}%{get(b:,'coc_current_function','')}
set statusline+=\ %{LinterStatus()}
set statusline+=\ %l:%c\ 
